### PR TITLE
Add basic OSS settings/files

### PR DESCRIPTION
**Pull request by SavePointSam**
After seeing this on Twitter yesterday, I got really excited seeing that you had made this logger available on NPM. After going to find it on the NPM website I noticed it was missing the link back to the GitHub repo. Originally, I wanted to just add that link. However, I took some liberties adding a few other features that I would consider fundamental / wanted as a user.

Adds:
- Prettier
- ES6 default export support
- exposes createLogger to consumer for custom loggers
- LICENSE
- basic README
- basic git dot files
- NPM registry

### CODE REVIEW

**Comment by SavePointSam** [comment]
ping @bvaughn

**Review by bvaughn — APPROVED** [review]
Thanks~

**Comment by bvaughn** [comment]
Ah, I didn't read it carefully enough before merging. Mind updating `source.js` heh?

**Comment by SavePointSam** [comment]
Oh! I didn't even see `source.js`. I thought you just happened to write everything for ES5 compatibility. Were you intending on just writing everything in `source.js` and then use the Babel REPL to update `index.js` manually since there isn't a build process baked in yet?

**Comment by bvaughn** [comment]
I published this between meetings at the request of someone on Twitter (without giving any thought to future updates).

Want to become a contributor? I'll add you to the repo.

**Comment by SavePointSam** [comment]
Sure!

**Comment by bvaughn** [comment]
I've added you as a maintainer.

What's your NPM username? I can add you to the package too.

**Comment by SavePointSam** [comment]
[savepointsam](https://www.npmjs.com/~savepointsam)

**Comment by bvaughn** [comment]
You've been invited!

**Pull request merged**
